import { z } from 'zod';
import {
  ATTR_NAMES,
  CommandPolicy,
  CommandType,
  StatusFlag,
  StatusHit,
  DamageKind,
  DamageOrigin,
  EffectType,
  HookAim,
  HookName,
  SkillTag,
  StatusCategory,
  TargetMode,
  TargetSide,
  UnitKind,
  type SkillEffect,
} from '../core';

export const jjId = z.string().regex(/^jiujie\.[a-z][a-z0-9_.]*$/);
const ref = z.string().min(1);
export const jjExpr = z.union([
  z.number().finite(),
  z.string().min(1).max(2000),
]);
export const jjTargeting = z.strictObject({
  side: z.enum(TargetSide),
  excludeSelf: z.boolean().optional(),
  maxSelected: z.number().int().positive().optional(),
  mode: z.enum(TargetMode).optional(),
  count: jjExpr.optional(),
  extraCount: jjExpr.optional(),
  extraChance: jjExpr.optional(),
  includeOwnedStatusKind: ref.optional(),
  requireKind: z.enum(UnitKind).optional(),
  includeDowned: z.boolean().optional(),
  includeDead: z.boolean().optional(),
  onlyDowned: z.boolean().optional(),
  requireStatusKinds: z.array(ref).optional(),
});
export const jjWhen = z.strictObject({
  expression: jjExpr.optional(),
  skillIds: z.array(ref).optional(),
  skillTags: z.array(z.enum(SkillTag)).optional(),
  requireKind: z.enum(DamageKind).optional(),
  damageOrigins: z.array(z.enum(DamageOrigin)).optional(),
  pvp: z.boolean().optional(),
  teamUniqueTag: ref.optional(),
  targetEnemy: z.boolean().optional(),
  targetHasStandingPet: z.boolean().optional(),
  actionKilledTarget: z.boolean().optional(),
  sourceStanding: z.boolean().optional(),
  actionSucceeded: z.boolean().optional(),
  sourceTags: z.array(ref).optional(),
  targetDowned: z.boolean().optional(),
  foeKind: z.enum(UnitKind).optional(),
  foeTags: z.array(ref).optional(),
  excludeFoeKinds: z.array(z.enum(UnitKind)).optional(),
  targetStatusKinds: z.array(ref).optional(),
  targetAbsentStatusKinds: z.array(ref).optional(),
  targetOwnedStatus: z
    .strictObject({ kind: ref, appliedThisRound: z.boolean().optional() })
    .optional(),
  requireStatusIds: z.array(ref).optional(),
  requireAbsentStatusIds: z.array(ref).optional(),
  removedStatusKind: ref.optional(),
  statusRemoveReason: ref.optional(),
  oncePerActionTarget: z.boolean().optional(),
  oncePerRound: z.boolean().optional(),
  oncePerBattle: z.boolean().optional(),
  initialTargetStatusKinds: z.array(ref).optional(),
  targetSlot: z.enum(['primary', 'secondary', 'normal']).optional(),
  initialTargetOwnedStatus: ref.optional(),
  sourceHpRatioBelow: z.number().optional(),
});
export const jjModifier = z.strictObject({
  when: jjWhen.optional(),
  hitAdd: jjExpr.optional(),
  sealChanceFactor: jjExpr.optional(),
  defenseIgnoreAdd: jjExpr.optional(),
  teamAura: ref.optional(),
  allDamageTakenBonus: jjExpr.optional(),
  damageBonus: jjExpr.optional(),
  damageAdd: jjExpr.optional(),
  damageTakenBonus: jjExpr.optional(),
  physicalAttackAdd: jjExpr.optional(),
  sealResistanceAdd: jjExpr.optional(),
  targetCountAdd: jjExpr.optional(),
});
const common = { when: jjWhen.optional(), targeting: jjTargeting.optional() };
export const jjEffect: z.ZodType<SkillEffect> = z.lazy(() =>
  z.discriminatedUnion('type', [
    z.strictObject({ ...common, type: z.literal(EffectType.Repeat), min: z.number().int().min(1).max(9), max: z.number().int().min(1).max(9), effects: z.array(jjEffect) }),
    z.strictObject({ ...common, type: z.literal(EffectType.SpellHit), coeff: z.number(), power: jjExpr.optional(), defenseIgnore: jjExpr.optional() }),
    z.strictObject({ ...common, type: z.literal(EffectType.DamageMp), power: jjExpr }),
    z.strictObject({ ...common, type: z.literal(EffectType.LoseHp), power: jjExpr }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.RandomBranch),
      branchId: ref,
      chance: jjExpr,
      successEffects: z.array(jjEffect),
      failureEffects: z.array(jjEffect),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.FixedHit),
      power: jjExpr,
      percentageDamage: z.boolean().optional(),
      cannotKill: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.PhysicalHit),
      coeff: z.number().nonnegative(),
      defenseIgnore: jjExpr.optional(),
      power: jjExpr.optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ApplyStatus),
      statusId: ref,
      duration: jjExpr,
      self: z.boolean().optional(),
      hit: z.enum(StatusHit).optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.RemoveStatus),
      statusIds: z.array(ref).optional(),
      kinds: z.array(ref).optional(),
      ownedOnly: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyStatusDuration),
      kinds: z.array(ref).optional(),
      categories: z.array(z.enum(StatusCategory)).optional(),
      maxCount: z.number().int().positive().optional(),
      random: z.boolean().optional(),
      amount: jjExpr,
      ownedOnly: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.Dispel),
      categories: z.array(z.enum(StatusCategory)).optional(),
      statusIds: z.array(ref).optional(),
      kinds: z.array(ref).optional(),
      immunityRounds: z.number().int().positive().optional(),
      maxCount: jjExpr.optional(),
      random: z.boolean().optional(),
      preventReapplyThisRound: z.boolean().optional(),
      excludeStatusFlags: z.array(z.enum(StatusFlag)).optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.Revive),
      hpRatio: jjExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.Heal),
      power: jjExpr,
      fixedBase: z.boolean().optional(),
      includeHealPower: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.RemoveWound),
      power: jjExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.RestoreHp),
      power: jjExpr,
      allowFatal: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyCooldown),
      skillId: ref,
      amount: jjExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyFact),
      key: ref,
      value: jjExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyResource),
      resourceId: ref,
      amount: jjExpr,
      mode: z.enum(['add', 'set']).optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyHeal),
      factor: jjExpr.optional(),
      add: jjExpr.optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyWound),
      factor: jjExpr.optional(),
      add: jjExpr.optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyStrike),
      factor: jjExpr.optional(),
      add: jjExpr.optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyChance),
      factor: jjExpr.optional(),
      add: jjExpr.optional(),
    }),
  ]),
);
export const jjHook = z.strictObject({
  on: z.enum(HookName),
  sourceIsSelf: z.boolean().optional(),
  sourceIsOwnedPet: z.boolean().optional(),
  targetIsSelf: z.boolean().optional(),
  requireKind: z.enum(DamageKind).optional(),
  aim: z.enum(HookAim).optional(),
  targeting: jjTargeting.optional(),
  chance: jjExpr.optional(),
  when: jjWhen.optional(),
  limitConsumption: z.enum(["onSuccess", "onAttempt"]).optional(),
  effects: z.array(jjEffect).min(1),
});
export const jjStatus = z.strictObject({
  school: z.literal("jiujie"),
  id: jjId,
  name: z.string().min(1),
  kind: jjId,
  category: z.enum(StatusCategory),
  dispellable: z.boolean().optional(),
  extendable: z.boolean().optional(),
  expireSameRound: z.boolean().optional(),
  untilBattleEnd: z.boolean().optional(),
  sourceBound: z.boolean().optional(),
  persistWhenDowned: z.boolean().optional(),
  snapshotModifiers: z.boolean().optional(),
  blockedCommands: z.array(z.enum(CommandType)).optional(),
  blocksNonArtSkills: z.boolean().optional(),
  blocksArts: z.boolean().optional(),
  blocksSpell: z.boolean().optional(),
  commandPolicy: z.enum(CommandPolicy).optional(),
  protectsTarget: z.boolean().optional(),
  upkeepMp: z.strictObject({ self: z.number(), other: z.number() }).optional(),
  modifiers: z.array(jjModifier).optional(),
  attrMods: z.partialRecord(z.enum(ATTR_NAMES), jjExpr).optional(),
  speedMod: jjExpr.optional(),
});
