import { z } from 'zod';
import {
  ATTR_NAMES,
  DamageKind,
  DamageOrigin,
  EffectType,
  HookAim,
  HookName,
  SkillTag,
  StatusCategory,
  TargetMode,
  TargetSide,
  UnitKind,
  type SkillEffect,
} from '../core';

export const wxId = z.string().regex(/^wuxiang\.[a-z][a-z0-9_.]*$/);
const ref = z.string().min(1);
export const wxExpr = z.union([
  z.number().finite(),
  z.string().min(1).max(2000),
]);
export const wxTargeting = z.strictObject({
  side: z.enum(TargetSide),
  mode: z.enum(TargetMode).optional(),
  count: wxExpr.optional(),
  extraCount: wxExpr.optional(),
  extraChance: wxExpr.optional(),
  includeOwnedStatusKind: ref.optional(),
  requireKind: z.enum(UnitKind).optional(),
  includeDowned: z.boolean().optional(),
  onlyDowned: z.boolean().optional(),
  requireStatusKinds: z.array(ref).optional(),
});
export const wxWhen = z.strictObject({
  expression: wxExpr.optional(),
  skillIds: z.array(ref).optional(),
  skillTags: z.array(z.enum(SkillTag)).optional(),
  requireKind: z.enum(DamageKind).optional(),
  damageOrigins: z.array(z.enum(DamageOrigin)).optional(),
  pvp: z.boolean().optional(),
  teamUniqueTag: ref.optional(),
  targetEnemy: z.boolean().optional(),
  targetHasStandingPet: z.boolean().optional(),
  actionKilledTarget: z.boolean().optional(),
  sourceStanding: z.boolean().optional(),
  actionSucceeded: z.boolean().optional(),
  sourceTags: z.array(ref).optional(),
  targetDowned: z.boolean().optional(),
  foeKind: z.enum(UnitKind).optional(),
  targetStatusKinds: z.array(ref).optional(),
  targetAbsentStatusKinds: z.array(ref).optional(),
  targetOwnedStatus: z
    .strictObject({ kind: ref, appliedThisRound: z.boolean().optional() })
    .optional(),
  requireStatusIds: z.array(ref).optional(),
  requireAbsentStatusIds: z.array(ref).optional(),
  removedStatusKind: ref.optional(),
  statusRemoveReason: ref.optional(),
  oncePerActionTarget: z.boolean().optional(),
  oncePerRound: z.boolean().optional(),
  oncePerBattle: z.boolean().optional(),
  initialTargetStatusKinds: z.array(ref).optional(),
  targetSlot: z.enum(['primary', 'normal']).optional(),
  initialTargetOwnedStatus: ref.optional(),
  sourceHpRatioBelow: z.number().optional(),
});
export const wxModifier = z.strictObject({
  when: wxWhen.optional(),
  hitAdd: wxExpr.optional(),
  allDamageTakenBonus: wxExpr.optional(),
  damageBonus: wxExpr.optional(),
  damageAdd: wxExpr.optional(),
  damageTakenBonus: wxExpr.optional(),
  physicalAttackAdd: wxExpr.optional(),
  sealResistanceAdd: wxExpr.optional(),
  targetCountAdd: wxExpr.optional(),
});
const common = { when: wxWhen.optional(), targeting: wxTargeting.optional() };
export const wxEffect: z.ZodType<SkillEffect> = z.lazy(() =>
  z.discriminatedUnion('type', [
    z.strictObject({
      ...common,
      type: z.literal(EffectType.RandomBranch),
      branchId: ref,
      chance: wxExpr,
      successEffects: z.array(wxEffect),
      failureEffects: z.array(wxEffect),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.FixedHit),
      power: wxExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.PhysicalHit),
      coeff: z.number().nonnegative(),
      power: wxExpr.optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ApplyStatus),
      statusId: ref,
      duration: wxExpr,
      self: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.RemoveStatus),
      statusIds: z.array(ref).optional(),
      kinds: z.array(ref).optional(),
      ownedOnly: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyStatusDuration),
      kinds: z.array(ref),
      amount: wxExpr,
      ownedOnly: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.Dispel),
      categories: z.array(z.enum(StatusCategory)),
      maxCount: wxExpr.optional(),
      random: z.boolean().optional(),
      preventReapplyThisRound: z.boolean().optional(),
      excludeStatusFlags: z.array(z.literal('blocksRevive')).optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.Revive),
      hpRatio: wxExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.Heal),
      power: wxExpr,
      fixedBase: z.boolean().optional(),
      includeHealPower: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.RemoveWound),
      power: wxExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.RestoreHp),
      power: wxExpr,
      allowFatal: z.boolean().optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyCooldown),
      skillId: ref,
      amount: wxExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyFact),
      key: ref,
      value: wxExpr,
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyResource),
      resourceId: ref,
      amount: wxExpr,
      mode: z.enum(['add', 'set']).optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyHeal),
      factor: wxExpr.optional(),
      add: wxExpr.optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyWound),
      factor: wxExpr.optional(),
      add: wxExpr.optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyStrike),
      factor: wxExpr.optional(),
      add: wxExpr.optional(),
    }),
    z.strictObject({
      ...common,
      type: z.literal(EffectType.ModifyChance),
      factor: wxExpr.optional(),
      add: wxExpr.optional(),
    }),
  ]),
);
export const wxHook = z.strictObject({
  on: z.enum(HookName),
  sourceIsSelf: z.boolean().optional(),
  targetIsSelf: z.boolean().optional(),
  requireKind: z.enum(DamageKind).optional(),
  aim: z.enum(HookAim).optional(),
  targeting: wxTargeting.optional(),
  chance: wxExpr.optional(),
  when: wxWhen.optional(),
  effects: z.array(wxEffect).min(1),
});
export const wxStatus = z.strictObject({
  id: wxId,
  name: z.string().min(1),
  kind: wxId,
  category: z.enum(StatusCategory),
  dispellable: z.boolean().optional(),
  extendable: z.boolean().optional(),
  expireSameRound: z.boolean().optional(),
  untilBattleEnd: z.boolean().optional(),
  sourceBound: z.boolean().optional(),
  persistWhenDowned: z.boolean().optional(),
  snapshotModifiers: z.boolean().optional(),
  modifiers: z.array(wxModifier).optional(),
  attrMods: z.partialRecord(z.enum(ATTR_NAMES), wxExpr).optional(),
  speedMod: wxExpr.optional(),
});
