/** Daoyou 首版梦幻式规则常量。公式只从此处取数，不在内容中散落。 */
export const DaoyouRule = {
  spellFluctuationMin: 0.95,
  spellFluctuationMax: 1.05,
  physicalFluctuationMin: 0.9,
  physicalFluctuationMax: 1.1,
  critMultiplier: 2,
  physicalFuryAtkMultiplier: 1.5,
  defendPhysicalFactor: 0.5,
  physicalCoefficient: 1.3,
  unbrokenDefRatio: 0.9,
  unbrokenAtkRatio: 0.1,
  cultivateRate: 0.02,
  cultivateFlat: 5,
  damageCultivateDiffMin: -20,
  damageCultivateDiffMax: 20,
  hitChanceFloor: 0.2,
  hitChanceCeil: 1,
  hitChanceBase: 0.5,
  hitChanceScale: 200,
  sealChanceFloor: 0.2,
  sealChanceCeil: 0.9,
  sealChanceBase: 0.55,
  sealLevelWeight: 2,
  sealCultivateWeight: 2,
  sealCultivateDiffMin: -10,
  sealCultivateDiffMax: 10,
  fleeChanceFloor: 0.1,
  fleeChanceCeil: 0.9,
  fleeChanceBase: 0.4,
  minDamage: 1,
  maxRounds: 150,
} as const
